service: exiftool-ruby-lambda-layer

provider:
  name: aws
  region: eu-west-1
  runtime: ruby2.5

layers:
  exiftool:
    path: layer
    include: ./**
    description: exiftool with ruby2.5
    compatibleRuntimes:
      - ruby2.5
    licenseInfo: MIT License
